--- # d22 formatting specifications

# Based on OJ's plotd22v5.py and v8 see email

dat:
    10min: [] # this is the basic report frequency
WM1: 
    name: WM1
    Hs: []
    Hmax: []
    EMC: []
    HEC: []
    Tp: []
    Tm02: []
    Tm10: []
    Tm01: []
    Mdir: []
    Pdir: []
WM2: 
    name: WM2
    Hs: []
    Hmax: []
    EMC: []
    HEC: []
    Tp: []
    Tm02: []
    Tm10: []
    Tm01: []
    Mdir: []
    Pdir: []

WM3: 
    name: WM3
    Hs: []
    Hmax: []
    EMC: []
    HEC: []
    Tp: []
    Tm02: []
    Tm10: []
    Tm01: []
    Mdir: []
    Pdir: []

WL1: 
    name: WL1
    Hlat: []

WL2: 
    name: WL2
    Hlat: []

WL3: 
    name: WL3
    Hlat: []

WIA: 
    name: WIA
    FF_10min_10m: []
    FF_10min_sensor: []
    DD_10min_sensor: []
    FF_2min: []
    DD_2min: []

WIB: 
    name: WIB
    FF_10min_10m: []
    FF_10min_sensor: []
    DD_10min_sensor: []
    FF_2min: []
    DD_2min: []

WIC: 
    name: WIC 
    FF_10min_10m: []
    FF_10min_sensor: []
    DD_10min_sensor: []
    FF_2min: []
    DD_2min: []

standard_name: 
    Hs: 'sea_surface_wave_significant_height'                       
    Mdir: 'sea_surface_wave_from_direction'
    Pdir: "sea_surface_wave_from_direction\
        _at_variance_spectral_density_maximum"
    Tm02: "sea_surface_wave_mean_period\
        _from_variance_spectral_density_second_frequency_moment"
    Tm01: "sea_surface_wave_mean_period\
        _from_variance_spectral_density_first_frequency_moment"
    Tm10: "sea_surface_wave_mean_period\
        _from_variance_spectral_density_inverse_frequency_moment"
    Tp: 'sea_surface_wave_period_at_variance_spectral_density_maximum'
    FF_10min_10m: 'wind_speed'
    FF_10min_sensor: 'wind_speed'
    DD_10min_sensor: 'wind_from_direction'

long_name: 
    Hs: "Significant wave height retrieved \
            at an imposed sampling interval of 10 min, \
            estimation method depends on instrument"
    Mdir: "Mean wave direction \
            at an imposed sampling interval of 10 min, \
            estimation method depends on instrument"
    Pdir: "Mean wave direction \
            at an imposed sampling interval of 10 min, \
            estimation method depends on instrument"
    Tp: "Peak wave period \
            at variance spectral density maximum \
            at an imposed sampling interval of 10 min, \
            estimation method depends on instrument"
    Tm02: "Mean wave period \
            from variance spectral density second frequency moment\
            at an imposed sampling interval of 10 min, \
            estimation method depends on instrument"
    Tm01: "Mean wave period \ 
            from variance spectral density first frequency moment\
            at an imposed sampling interval of 10 min, \
            estimation method depends on instrument"
    Tm10: "Mean wave period \
            from variance spectral density inverse frequency moment \
            at an imposed sampling interval of 10 min, \
            estimation method depends on instrument"
    FF_10min_10m: "10 min wind speed at 10m artificially reduced"
    FF_10min_sensor: "10 min wind speed at sensor height"
    DD_10min_sensor: "10 min wind direction at sensor height"

units:
    Hs: 'm'
    Mdir: 'degree'
    Pdir: 'degree'
    Tm02: 's'
    Tm01: 's'
    Tm10: 's'
    Tp: 's'
    FF_10min_10m: 'm s-1'
    FF_10min_sensor: 'm s-1'
    DD_10min_sensor: 'degree'

convention:
    Hs: 'NA'
    Mdir: 'meteorologic'
    Pdir: 'meteorologic'
    Tm02: 'NA'
    Tm01: 'NA'
    Tm10: 'NA'
    Tp: 'NA'
    FF_10min_10m: 'NA'
    FF_10min_sensor: 'NA'
    DD_10min_sensor: 'meteorologic'

valid_range:
    Hs: [0., 25.]
    Mdir: [0., 360.]
    Pdir: [0., 360.]
    Tm02: [0., 30.]
    Tm01: [0., 30.]
    Tm10: [0., 30.]
    Tp: [0., 30.]
    FF_10min_10m: [0.,150.]
    FF_10min_sensor: [0.,150.]
    DD_10min_sensor: [0., 360.]
