--- # storage of important paths
# """
#    structure local files: 
#          location (local/remote) 
#        + type (station/satellite) 
#        + format (d22/nc)
#    structure remote files:
#          network_protocol (FTP/FTPS/SFTP)
#        + type (station/satellite)
#        + productname
# """

local:
    station:
        d22: "/lustre/storeB/immutable/archive/projects/\
             metproduction/DNMI_OFFSHORE/"
             # +rig+'/d22/'+YY+'/'+dy+'.d22'
        nc: "/opdata/offshore/" #+rig+'/d22/'+dy+'.d22'
    satellite: /lustre/storeA/project/fou/om/altimeter/

remote:
    FTP:
        satellite:
            cmems_014_001: "/Core/\
                        WAVE_GLO_WAV_L3_SWH_NRT_OBSERVATIONS_014_001/\
                        dataset-wav-alti-l3-swh-rt-global-satID"
