--- # specifications for satellite missions

# """
# structure local files: 
#        + instrument type (altimeter/scatterometer) 
#        + provider (eumetsat/cmems)
#        + specs
# """

altimeter:
    eumetsat:
        level: 2
        satellite: s3a, s3b
        local:
            path:
        remote:
            path:
            server:
    cmems:
        level: 3
        satellite: s3a, s3b, c2, al, j3, h2b
        local:
            path:
        remote: 
            path: "/Core/\
                   WAVE_GLO_WAV_L3_SWH_NRT_OBSERVATIONS_014_001/\
                   dataset-wav-alti-l3-swh-rt-global-"
            server: "nrt.cmems-du.eu"

scatterometer:
    cmems:
        level: 3
        satellite: cfo
        local:
            path:
        remote: 
            path: "/Core/\
                   WAVE_GLO_WAV_L3_SWH_NRT_OBSERVATIONS_014_001/\
                   dataset-wav-alti-l3-swh-rt-global-"
            server: "nrt.cmems-du.eu"
