--- # specifications for satellite missions

# """
# structure local files: 
#        + instrument type (altimeter/scatterometer) 
#        + provider (eumetsat/cmems)
#        + specs
# """

altimeter:
    eumetsat:
        level: 2
        satellite: s3a, s3b
        local:
            path:
        remote:
            path:
            server:
        misc:
    cmems:
        level: 3
        satellite: s3a,s3b,c2,al,j3,h2b,cfo # do not use space
        local:
            path: /home/patrikb/tmp_altimeter
        remote: 
            path: "/Core/\
                   WAVE_GLO_WAV_L3_SWH_NRT_OBSERVATIONS_014_001/\
                   dataset-wav-alti-l3-swh-rt-global-"
            server: "nrt.cmems-du.eu"
        misc:
            vardef: # stdname: abbreviation
                sea_surface_wave_significant_height: VAVH
