--- # off-shore location specifications

path:
    platform:
        local: 
            d22: 
                path_template: ["/lustre/storeB/immutable/archive/projects/\
                                metproduction/DNMI_OFFSHORE/platform/d22/%Y/", 
                                "/vol/gorgon/offshore/platform/d22/"]
                file_template: '%Y%m%d.d22'
                strsub: ['platform'] # part of string to be substituted
            nc: 
                path_template: ["/home/patrikb/tmp_station/%Y/%m/",
                                "/lustre/storeB/project/fou/om/\
                                 waveverification/obs/stations/%Y/%m/"]
                file_template: 'varalias_10min_platform_sensor_%Y%m.nc'
                strsub: ['varalias','platform','sensor']
        remote:
        misc:
            vardef: # stdname: abbreviation
                #sea_surface_wave_significant_height: Hs_10min
platform:
    asgardb:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 65.11
            lon: 6.79
        operator: Equinor_Energy
#    aastahansteen:
#        sensor:
#        manufacturer:
#        coords:
#        operator: Equinor_Energy
#    brage:
#        sensor:
#        manufacturer:
#        coords:
#        operator: Wintershall_Dea_Norge
    draugen:
        sensor:
            MKIIIradar: 0 # python indexing
            MKIIIradar: 1
        manufacturer:
            MKIIIradar: Miros
            MKIIIradar: Miros
        coords:
            lat: 64.35
            lon: 7.78
        operator: OKEA
    ekofiskL:
        sensor:
            waverider: 0 # python indexing
            OptechLaser: 1
            SAABWaveRadar: 2
        manufacturer:
            waverider: Datawell
            OptechLaser: Optech
            SAABWaveRadar: Rosemount
        coords:
            lat: 56.54
            lon: 3.21
        operator: ConocoPhillips_Skandinavia
    gjoa:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 61.33
            lon: 3.9
        operator: Neptun_Energy_Norge
#    goliat:
#        sensor:
#        manufacturer:
#        coords:
#        operator: VarEnergi
    grane:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 59.17
            lon: 2.48
        operator: Equinor_Energy
#    gudrun:
#        sensor:
#        manufacturer:
#        coords:
#        operator: Equinor_Energy
    oseberg:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 60.5
            lon: 2.8
        operator: NA
    gullfaksc:
        sensor: 
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 56.28
            lon: 3.39
        operator: Equinor_Energy
    heidrun:
        sensor:
            NA_1: 0 # python indexing
            NA_2: 1
        manufacturer:
            NA_1: NA
            NA_2: NA
        coords:
            lat: 65.32
            lon: 7.32
        operator: Equinor_Energy
    heimdal:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 59.57
            lon: 2.23
        operator: Equinor_Energy
#    kvitebjorn:
#        sensor:
#        manufacturer:
#        coords:
#        operator: Equinor_Energy
#    kristin:
#        sensor:
#        manufacturer:
#        coords:
#        operator: Equinor_Energy
#    huldra:
#        sensor:
#        manufacturer:
#        coords:
#        operator: Equinor_Energy
#    njord:
#        sensor:
#        manufacturer:
#        coords:
#        operator: Equinor_Energy
    norne:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 66.02
            lon: 8.08
        operator: Equinor_Energy
#    ormenlange:
#        sensor:
#        manufacturer:
#        coords:
#        operator: NorskeShell
    snorrea:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 61.45
            lon: 2.15
        operator: Equinor_Energy
#    snorreb:
#        sensor:
#            NA_1: 0 # python indexing
#        manufacturer:
#            NA_1: NA
#        coords:
#            lat: 61.52
#            lon: 2.21
#        operator: Equinor_Energy
    sleipner:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 58.37
            lon: 1.91
        operator: Equinor_Energy
    stafjorda: # established typo should be stafjord
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 61.25
            lon: 1.85
        operator: Equinor_Energy
#    statfjordb:
#        sensor:
#            NA_1: 0 # python indexing
#        manufacturer:
#            NA_1: NA
#        coords:
#            lat: 61.20
#            lon: 1.83
#        operator: Equinor_Energy
    trolla:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 60.64
            lon: 3.72
        operator: Equinor_Energy
    trollb:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 60.77
            lon: 3.5
        operator: Equinor_Energy
#    ula:
#       sensor:
#           NA_1: 0 # python indexing
#       manufactor:
#           NA_1: NA
#       coord:
#           lat: 57.10
#           lon:  2.85
#       operator: Aker_BP
    valhall:
        sensor:
            SAABWaveRadar_1: 0 # python indexing
            SAABWaveRadar_2: 1
        manufacturer:
            SAABWaveRadar_1: Rosemount
            SAABWaveRadar_2: Rosemount
        coords:
            lat: 56.28
            lon: 3.39
        operator: Aker_BP
#    veslefrikka:
#        sensor:
#        manufacturer:
#        coords:
#        operator: Equinor_Energy
#    veslefrikkb:
#        sensor:
#        manufacturer:
#        coords:
#        operator: Equinor_Energy
    visund:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 61.37
            lon: 2.46
        operator: Equinor_Energy
