--- # Additional information on variables 
# cf convention together with variable alias for wavy
# http://cfconventions.org/Data/cf-standard-names/69/build/cf-standard-name-table.html
# This config file sets the standard for how variables are handled 
# and treated within wavy as well as for the wavy putput files

#time
time:
    standard_name: time
    units: seconds since

# coordinates
lons: 
    standard_name: longitude
    units: degree_east
lats: 
    standard_name: latitude
    units: degree_north

# variables
Hs:
    standard_name: sea_surface_wave_significant_height
    units: m
    long_name:
    valid_range: [0., 30.]
    convention:
Tp:
    standard_name: sea_surface_wave_period_at_variance_spectral_density_maximum
    units: s
    valid_range: [0., 30.]
    convention:
Tm01:
    standard_name: sea_surface_wave_mean_period_from_variance_spectral_density_first_frequency_moment
    units: s
    valid_range: [0., 30.]
    convention:
Tm02:
    standard_name: sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment
    units: s
    valid_range: [0., 30.]
    convention:
Tm10:
    standard_name: sea_surface_wave_mean_period_from_variance_spectral_density_inverse_frequency_moment
    units: s
    valid_range: [0., 30.]
    convention:
Pdir:
    standard_name: sea_surface_wave_to_direction_at_variance_spectral_density_maximum
    units: degree
    valid_range: [0.,360.]
    convention: oceanographic
Mdir:
    standard_name: sea_surface_wave_to_direction
    units: degree
    valid_range: [0.,360.]
    convention: oceanographic
ux:
    standard_name: x_wind
    alias: grid_eastward_wind
    units: m/s
ua: 
    standard_name: eastward_wind
    units: m/s
vy: 
    standard_name: y_wind 
    alias: grid_northward_wind
    units: m/s
va: 
    standard_name: northward_wind
    units: m/s
U: 
    standard_name: wind_speed
    units: m/s
