--- # variable shortcut information table

time: time
Hs: sea_surface_wave_significant_height
Tp: sea_surface_wave_period_at_variance_spectral_density_maximum
Tm01: sea_surface_wave_mean_period_from_variance_spectral_density_first_frequency_moment
Tm02: sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment
Tm10: sea_surface_wave_mean_period_from_variance_spectral_density_inverse_frequency_moment
Pdir: sea_surface_wave_to_direction_at_variance_spectral_density_maximum
Mdir: sea_surface_wave_to_direction
